// Code generated by goctl. DO NOT EDIT.
package types

type CommonResp struct {
	Success bool   `json:"success"`
	Detail  string `json:"detail,omitempty"`
}

type CommitOrderReq struct {
	ProductName          string `json:"productName"`
	ProductNumber        int32  `json:"productNumber"`
	PayMethod            int32  `json:"payMethod"`
	DeliveryMethod       int32  `json:"deliveryMethod"`
	ExpectedDeliveryTime string `json:"expectedDeliveryTime"`
}

type CommitOrderResp struct {
	CommonResp
	OrderID string `json:"orderID"`
}
