// Code generated by goctl. DO NOT EDIT.
package types

type CommonResp struct {
	Success bool   `json:"success"`
	Detail  string `json:"detail,omitempty"`
}

type RegisterReq struct {
	AccountName string `json:"accountName"`
	Password    string `json:"password"`
}

type RegisterResp struct {
	CommonResp
}

type UnRegisterReq struct {
	AccountName string `form:"accountName"`
}

type UnRegisterResp struct {
	CommonResp
}

type LoginReq struct {
	AccountName string `json:"accountName"`
	Password    string `json:"password"`
}

type LoginResp struct {
	CommonResp
	Token string `json:"token"`
}

type LogoutReq struct {
	AccountName string `form:"accountName"`
}

type LogoutResp struct {
	CommonResp
}
